#!/usr/bin/env python3
# Copyright 2023 Canonical Ltd.
# Licensed under the Apache2.0. See LICENSE file in charm source for details.

"""Library for interacting with a OpenBao cluster.

This library shares operations that interact with OpenBao through its API. It is
intended to be used by charms that need to manage a OpenBao cluster.
"""

import logging
from abc import abstractmethod
from dataclasses import dataclass
from enum import Enum
from io import IOBase
from typing import List, MutableMapping, Optional, Protocol

import requests
from requests.exceptions import ConnectionError, RequestException

from openbao.openbao_http import (
    ForbiddenError,
    HttpError,
    InternalServerError,
    InvalidPathError,
    InvalidRequestError,
    OpenBaoHttp,
)

RAFT_STATE_ENDPOINT = "v1/sys/storage/raft/autopilot/state"


class LogAdapter(logging.LoggerAdapter):
    """Adapter for the logger to prepend a prefix to all log lines."""

    prefix = "openbao_client"

    def process(self, msg: str, kwargs: MutableMapping) -> tuple[str, MutableMapping]:
        """Decides the format for the prepended text."""
        return f"[{self.prefix}] {msg}", kwargs


logger = LogAdapter(logging.getLogger(__name__), {})


@dataclass
class Token:
    """Class that represents token authentication for openbao.

    This method is the most basic and always available method to access openbao.
    """

    token: str

    def login(self, client: OpenBaoHttp) -> None:
        """Authenticate a openbao client with a token."""
        client.token = self.token


@dataclass
class AppRole:
    """Class that represents approle authentication for openbao.

    This method is primarily used to authenticate automation programs for openbao.
    """

    role_id: str
    secret_id: str

    def login(self, client: OpenBaoHttp) -> None:
        """Authenticate a openbao client with approle details."""
        response = client.post(
            "/v1/auth/approle/login",
            json={"role_id": self.role_id, "secret_id": self.secret_id},
        )
        client.token = response.json()["auth"]["client_token"]


class AuthMethod(Protocol):
    """Classes that implement a login method are auth methods used to log in to OpenBao."""

    @abstractmethod
    def login(self, client: OpenBaoHttp) -> None:
        """Log in using the given method."""
        raise NotImplementedError


@dataclass
class Certificate:
    """Class that represents a certificate generated by the PKI secrets engine."""

    certificate: str
    ca: str
    chain: List[str]


class AuditDeviceType(Enum):
    """Class that represents the devices that openbao supports as device types for audit."""

    FILE = "file"
    SYSLOG = "syslog"
    SOCKET = "socket"


class SecretsBackend(Enum):
    """Class that represents the supported secrets backends by OpenBao."""

    KV_V2 = "kv-v2"
    PKI = "pki"
    TRANSIT = "transit"


class OpenBaoClientError(Exception):
    """Base class for exceptions raised by the OpenBao client."""


class OpenBaoAuthenticationError(OpenBaoClientError):
    """Raised when OpenBao explicitly rejects authentication credentials.

    This is raised for definitive authentication failures (e.g. invalid
    credentials, locked-out users) as opposed to transient errors (e.g.
    connection errors, OpenBao being sealed or unavailable).
    """


class PKICertificateError(OpenBaoClientError):
    """Raised when the PKI engine fails to sign a certificate request."""


class OpenBaoClient:
    """Class to interact with OpenBao through its API."""

    def __init__(self, url: str, ca_cert_path: str | None, timeout: int = 30):
        self._client = OpenBaoHttp(
            url=url, verify=ca_cert_path if ca_cert_path else False, timeout=timeout
        )

    def authenticate(self, auth_details: AuthMethod) -> bool:
        """Find and use the token related with the given auth method.

        Returns:
            bool: True if the authentication was successful and the token was
                accepted by openbao. False if the authentication failed due to a
                transient error (e.g. connection error, OpenBao unavailable).

        Raises:
            OpenBaoAuthenticationError: If OpenBao explicitly rejected the credentials
                (e.g. invalid credentials, user lockout).
        """
        try:
            auth_details.login(self._client)
            self._client.get("/v1/auth/token/lookup-self")
        except (ForbiddenError, InvalidRequestError) as e:
            logger.warning("OpenBao rejected authentication credentials: %s", e)
            raise OpenBaoAuthenticationError(str(e)) from e
        except (HttpError, ConnectionError) as e:
            logger.warning("Failed login to OpenBao: %s", e)
            return False
        return True

    @property
    def token(self) -> str:
        """Return the token used to authenticate with OpenBao."""
        return self._client.token

    def is_api_available(self) -> bool:
        """Return whether OpenBao is available."""
        try:
            self._client.request(
                "head",
                "/v1/sys/health",
                params={"standbyok": "true"},
                raise_on_error=False,
            )
            return True
        except (HttpError, RequestException) as e:
            logger.error("Error while checking OpenBao health status: %s", e)
            return False

    def is_initialized(self) -> bool:
        """Return whether OpenBao is initialized."""
        return self._client.get("/v1/sys/init").json()["initialized"]

    def is_sealed(self) -> bool:
        """Return whether OpenBao is sealed."""
        try:
            return self._read_seal_status()["sealed"]
        except HttpError as e:
            # This seems to happen if the seal status is checked immediately
            # after initializing the openbao when autounseal is enabled.
            # There is a short period of time where the openbao is initialized,
            # but hasn't finished setting up the autounseal configuration yet,
            # and the server will return an internal server error during this
            # period:
            #
            # InternalServerError (HTTP 500):
            # core: barrier reports initialized but no seal configuration found
            logger.error("Error while checking OpenBao seal status: %s", e)
            raise OpenBaoClientError(e) from e

    def _read_seal_status(self) -> dict:
        """Read the seal status of OpenBao."""
        return self._client.get("/v1/sys/seal-status").json()

    def is_available_initialized_and_unsealed(self) -> bool:
        """Return whether OpenBao is available, initialized and unsealed.

        In case of a transient error, it will return False.
        """
        try:
            return self.is_api_available() and self.is_initialized() and not self.is_sealed()
        except OpenBaoClientError as e:
            logger.error("Error while checking OpenBao status: %s", e)
            return False

    def read(self, path: str) -> dict:
        """Read the data at the given path."""
        try:
            response = self._client.get(f"/v1/{path}")
        except InvalidPathError:
            return {}
        except HttpError as e:
            logger.error("Error while reading data from %s: %s", path, e)
            return {}
        try:
            data = response.json()
        except ValueError:
            return {}
        return data.get("data", {})

    def write(self, path: str, data: dict) -> bool:
        """Write the data at the given path."""
        try:
            response = self._client.post(f"/v1/{path}", json=data)
        except HttpError as e:
            logger.error("Error while writing data to %s: %s", path, e)
            return False
        logger.info("Wrote data to %s: %s", path, response)
        return True

    def list(self, path: str) -> List[str]:
        """List the keys at the given path."""
        try:
            response = self._client.list_get_fallback(f"/v1/{path}")
        except InvalidPathError:
            return []
        except HttpError as e:
            logger.error("Error while listing keys at %s: %s", path, e)
            return []
        try:
            data = response.json()
        except ValueError:
            return []
        try:
            return data["data"]["keys"]
        except KeyError:
            return []

    def needs_migration(self) -> bool:
        """Return true if the openbao needs to be migrated, false otherwise."""
        return self._read_seal_status()["migration"]

    def get_seal_type(self) -> str:
        """Return the seal type of the OpenBao."""
        return self._read_seal_status()["type"]

    def is_seal_type_transit(self) -> bool:
        """Return whether OpenBao is sealed by the transit backend."""
        return "transit" == self.get_seal_type()

    def _health_status_code(self, standby_ok: bool = False) -> int:
        """Return the HTTP status code of the OpenBao health endpoint."""
        params = {"standbyok": "true"} if standby_ok else None
        response = self._client.request(
            "head", "/v1/sys/health", params=params, raise_on_error=False
        )
        return response.status_code

    def is_active(self) -> bool:
        """Return whether the OpenBao node is active or not.

        Returns:
            True if initialized, unsealed and active, False otherwise.
        """
        try:
            return self._health_status_code() == 200
        except (HttpError, RequestException) as e:
            logger.error("Error while checking OpenBao health status: %s", e)
            return False

    def is_active_or_standby(self) -> bool:
        """Return the health status of OpenBao.

        Returns:
            True if initialized, unsealed and active or standby, False otherwise.
        """
        try:
            return self._health_status_code() in (200, 429)
        except (HttpError, RequestException) as e:
            logger.error("Error while checking OpenBao health status: %s", e)
            return False

    def enable_audit_device(self, device_type: AuditDeviceType, path: str) -> None:
        """Enable a new audit device at the supplied path if it isn't already enabled.

        Args:
            device_type: One of three available device types
            path: The path that will receive audit logs
        """
        try:
            self._client.post(
                f"/v1/sys/audit/{device_type.value}",
                json={"type": device_type.value, "options": {"file_path": path}},
            )
            logger.info("Enabled audit device `%s` for path `%s`", device_type.value, path)
        except InvalidRequestError as e:
            if not e.json or not isinstance(e.json, dict):
                raise OpenBaoClientError(e) from e
            errors = e.json.get("errors", [])
            if len(errors) == 1 and errors[0].startswith("path already in use"):
                logger.info("Audit device already enabled.")
            else:
                raise OpenBaoClientError(e) from e
        except HttpError as e:
            raise OpenBaoClientError(e) from e

    def enable_approle_auth_method(self) -> None:
        """Enable approle auth method if it isn't already enabled."""
        try:
            self._client.post("/v1/sys/auth/approle", json={"type": "approle"})
            logger.info("Enabled approle auth method.")
        except InvalidRequestError as e:
            if not e.json or not isinstance(e.json, dict):
                raise OpenBaoClientError(e) from e
            errors = e.json.get("errors", [])
            if len(errors) == 1 and errors[0].startswith("path is already in use"):
                logger.info("Approle already enabled.")
            else:
                raise OpenBaoClientError(e) from e
        except HttpError as e:
            raise OpenBaoClientError(e) from e

    def create_or_update_policy_from_file(
        self, name: str, path: str, **formatting_args: str
    ) -> None:
        """Create/update a policy within openbao, using the file contents as the policy.

        Args:
            name: Name of the policy to create
            path: The path of the file where the policy is defined, ending with .hcl
            **formatting_args: Additional arguments to format the policy
        """
        # TODO: Remove this method when it is no longer needed. Prefer create_or_update_policy.
        with open(path, "r") as f:
            policy = f.read()
        self.create_or_update_policy(
            name, policy if not formatting_args else policy.format(**formatting_args)
        )

    def create_or_update_policy(self, name: str, content: str) -> None:
        """Create/update a policy within openbao.

        Args:
            name: Name of the policy to create
            content: The policy content
        """
        try:
            self._client.put(f"/v1/sys/policy/{name}", json={"policy": content})
        except HttpError as e:
            raise OpenBaoClientError(e) from e
        logger.debug("Created or updated charm policy: %s", name)

    def create_or_update_approle(
        self,
        name: str,
        token_ttl: str | None = None,
        token_max_ttl: str | None = None,
        policies: List[str] | None = None,
        cidrs: List[str] | None = None,
        token_period: str | None = None,
    ) -> str:
        """Create/update a role within openbao associating the supplied policies.

        Args:
            name: Name of the role to be created or updated
            policies: The attached list of policy names this approle will have access to
            token_ttl: Incremental lifetime for generated tokens, provided as a duration string such as "5m"
            token_max_ttl: Maximum lifetime for generated tokens, provided as a duration string such as "5m"
            token_period: The period within which the token must be renewed. See OpenBao documentation for more information.
            cidrs: The list of IP networks that are allowed to authenticate
        """
        params: dict = {"bind_secret_id": "true"}
        if token_ttl is not None:
            params["token_ttl"] = token_ttl
        if token_max_ttl is not None:
            params["token_max_ttl"] = token_max_ttl
        if policies is not None:
            params["token_policies"] = ",".join(policies)
        if cidrs is not None:
            params["token_bound_cidrs"] = ",".join(cidrs)
        if token_period is not None:
            params["token_period"] = token_period
        self._client.post(f"/v1/auth/approle/role/{name}", json=params)
        response = self._client.get(f"/v1/auth/approle/role/{name}/role-id").json()
        return response["data"]["role_id"]

    def generate_role_secret_id(self, name: str, cidrs: List[str] | None = None) -> str:
        """Generate a new secret tied to an AppRole."""
        params: dict = {}
        if cidrs is not None:
            params["cidr_list"] = ",".join(cidrs)
        response = self._client.post(f"/v1/auth/approle/role/{name}/secret-id", json=params).json()
        return response["data"]["secret_id"]

    def read_role_secret(self, name: str, id: str) -> dict:
        """Get definition of a secret tied to an AppRole."""
        try:
            response = self._client.post(
                f"/v1/auth/approle/role/{name}/secret-id/lookup", json={"secret_id": id}
            ).json()
        except (HttpError, KeyError) as e:
            raise OpenBaoClientError(e) from e
        return response["data"]

    def enable_secrets_engine(self, backend_type: SecretsBackend, path: str) -> None:
        """Enable given secret engine on the given path."""
        try:
            self._client.post(
                f"/v1/sys/mounts/{path}",
                json={
                    "type": backend_type.value,
                    "description": f"Charm created '{backend_type.value}' backend",
                },
            )
            logger.info("Enabled %s backend", backend_type.value)
        except InvalidRequestError as e:
            if not e.json or not isinstance(e.json, dict):
                raise OpenBaoClientError(e) from e
            errors = e.json.get("errors", [])
            if len(errors) == 1 and errors[0].startswith("path is already in use"):
                logger.info("%s backend already enabled", backend_type.value)
            else:
                raise OpenBaoClientError(e) from e

    def disable_secrets_engine(self, path: str) -> None:
        """Disable the secret engine at the given path."""
        try:
            self._client.delete(f"/v1/sys/mounts/{path}")
            logger.info("Disabled secret engine at %s", path)
        except InvalidPathError:
            logger.info("Secret engine at `%s` is already disabled", path)

    def get_intermediate_ca(self, mount: str) -> str:
        """Get the intermediate CA for the PKI backend."""
        return self._client.get(f"/v1/{mount}/ca/pem").text

    def generate_self_signed_ca(
        self,
        mount: str,
        common_name: str,
        ttl: str,
        sans_dns: Optional[List[str]] = None,
        country: Optional[str] = None,
        province: Optional[str] = None,
        locality: Optional[str] = None,
        organization: Optional[str] = None,
        organizational_unit: Optional[str] = None,
    ) -> tuple[str, str]:
        """Generate a self-signed CA using OpenBao's PKI root/generate/exported endpoint.

        Args:
            mount: The PKI mount point.
            common_name: The common name for the CA certificate.
            ttl: The TTL for the CA certificate, e.g. "8760h".
            sans_dns: Optional list of DNS subject alternative names.
            country: Optional country name.
            province: Optional province/state name.
            locality: Optional locality name.
            organization: Optional organization name.
            organizational_unit: Optional organizational unit name.

        Returns:
            tuple: (certificate_pem, private_key_pem)

        Raises:
            OpenBaoClientError: If OpenBao fails to generate the CA.
        """
        extra_params: dict = {"ttl": ttl}
        if sans_dns:
            extra_params["alt_names"] = ",".join(sans_dns)
        if country:
            extra_params["country"] = country
        if province:
            extra_params["province"] = province
        if locality:
            extra_params["locality"] = locality
        if organization:
            extra_params["organization"] = organization
        if organizational_unit:
            extra_params["organizational_unit"] = organizational_unit
        try:
            response = self._client.post(
                f"/v1/{mount}/root/generate/exported",
                json={"common_name": common_name, **extra_params},
            ).json()
            data = response["data"]
            return str(data["certificate"]), str(data["private_key"])
        except HttpError as e:
            raise OpenBaoClientError(e) from e

    def import_ca_certificate_and_key(self, mount: str, certificate: str, private_key: str):
        """Import the CA certificate and private key for the PKI backend."""
        pem_bundle = generate_pem_bundle(certificate=certificate, private_key=private_key)
        self._client.post(f"/v1/{mount}/config/ca", json={"pem_bundle": pem_bundle})

    def sign_pki_certificate_signing_request(
        self,
        mount: str,
        role: str,
        csr: str,
        common_name: str,
        ttl: str,
    ) -> Certificate:
        """Sign a certificate signing request for the PKI backend.

        Args:
            mount: The PKI mount point.
            role: The role to use for signing the certificate.
            csr: The certificate signing request.
            common_name: The common name for the certificate.
            ttl: The relative validity for the certificate.
                Should be a string in the format of a number with a unit such as
                "120m", "10h" or "90d".

        Returns:
            Certificate: The signed certificate object

        Raises:
            PKICertificateError: If the PKI engine fails to sign the certificate request.
        """
        try:
            response = self._client.post(
                f"/v1/{mount}/sign/{role}",
                json={"csr": csr, "common_name": common_name, "ttl": ttl},
            ).json()
            logger.info("Signed a PKI certificate for %s", common_name)
            return Certificate(
                certificate=response["data"]["certificate"],
                ca=response["data"]["issuing_ca"],
                chain=response["data"]["ca_chain"],
            )
        except (
            InvalidRequestError,
            ForbiddenError,
            InternalServerError,
            ConnectionError,
            RequestException,
        ) as e:
            logger.warning("PKI error while signing certificate: %s", e)
            raise PKICertificateError(e) from e

    def create_or_update_pki_charm_role(
        self,
        role: str,
        allowed_domains: str,
        max_ttl: str,
        mount: str,
        allow_bare_domains: bool | None,
        allow_subdomains: bool | None,
        allow_wildcard_certificates: bool | None,
        allow_any_name: bool | None,
        allow_ip_sans: bool,
        organization: str | None,
        organizational_unit: str | None,
        country: str | None,
        province: str | None,
        locality: str | None,
    ) -> None:
        """Create a role for the PKI backend or update it if it already exists.

        Args:
            role: The name of the role to create or update.
            allowed_domains: The list of allowed domains for the role.
            allow_bare_domains: Whether the exact allowed domains themselves can be issued.
            max_ttl: The maximum TTL for the role.
                It is also used by OpenBao as a maximum validity for the certificates issued by this role.
                Should be a string in the format of a number with a unit such as
                "120m", "10h" or "90d".
            mount: The mount point of the PKI backend for which the role will be created.
            allow_subdomains: Whether to allow issuing certificates for subdomains.
            allow_wildcard_certificates: Whether to allow issuing wildcard certificates.
            allow_any_name: Whether to allow issuing certificates for any name.
            allow_ip_sans: Whether to allow issuing certificates with IP Subject Alternative Names.
            organization: The organization for the role.
            organizational_unit: The organizational unit for the role.
            country: The country for the role.
            province: The province for the role.
            locality: The locality for the role.
        """
        extra_params = {
            "allowed_domains": allowed_domains,
            "max_ttl": max_ttl,
        }

        if allow_bare_domains is not None:
            extra_params["allow_bare_domains"] = "true" if allow_bare_domains else "false"
        if allow_subdomains is not None:
            extra_params["allow_subdomains"] = "true" if allow_subdomains else "false"
        if allow_wildcard_certificates is not None:
            extra_params["allow_wildcard_certificates"] = (
                "true" if allow_wildcard_certificates else "false"
            )
        if allow_any_name is not None:
            extra_params["allow_any_name"] = "true" if allow_any_name else "false"
        extra_params["allow_ip_sans"] = "true" if allow_ip_sans else "false"
        if organization:
            extra_params["organization"] = organization
        if organizational_unit:
            extra_params["organizational_unit"] = organizational_unit
        if country:
            extra_params["country"] = country
        if province:
            extra_params["province"] = province
        if locality:
            extra_params["locality"] = locality

        self._client.post(f"/v1/{mount}/roles/{role}", json=extra_params)

        log_params = ", ".join(f"{key}={value}" for key, value in extra_params.items())
        logger.info(
            "Created or updated PKI role `%s` with %s",
            role,
            log_params,
        )

    def create_or_update_acme_role(
        self,
        role: str,
        mount: str,
        max_ttl: str,
        allowed_domains: str,
        allow_bare_domains: bool | None,
        allow_subdomains: bool | None,
        allow_wildcard_certificates: bool | None,
        allow_any_name: bool | None,
        allow_ip_sans: bool,
        organization: str | None,
        organizational_unit: str | None,
        country: str | None,
        province: str | None,
        locality: str | None,
    ) -> None:
        """Create a role for the ACME backend or update it if it already exists.

        Args:
            role: The name of the role to create or update.
            allowed_domains: The list of allowed domains for the role.
            allow_bare_domains: Whether the exact allowed domains themselves can be issued.
            max_ttl: The maximum TTL for the role.
                It is also used by OpenBao as a maximum validity for the certificates issued by this role.
                Should be a string in the format of a number with a unit such as
                "120m", "10h" or "90d".
            mount: The mount point of the PKI backend for which the role will be created.
            allow_subdomains: Whether to allow issuing certificates for subdomains.
            allow_wildcard_certificates: Whether to allow issuing wildcard certificates.
            allow_any_name: Whether to allow issuing certificates for any name.
            allow_ip_sans: Whether to allow issuing certificates with IP Subject Alternative Names.
            organization: The organization for the role.
            organizational_unit: The organizational unit for the role.
            country: The country for the role.
            province: The province for the role.
            locality: The locality for the role.
        """
        self.create_or_update_pki_charm_role(
            role=role,
            mount=mount,
            max_ttl=max_ttl,
            allow_bare_domains=allow_bare_domains,
            allow_subdomains=allow_subdomains,
            allow_wildcard_certificates=allow_wildcard_certificates,
            allow_any_name=allow_any_name,
            allow_ip_sans=allow_ip_sans,
            organization=organization,
            organizational_unit=organizational_unit,
            country=country,
            province=province,
            locality=locality,
            allowed_domains=allowed_domains,
        )

    def is_pki_role_created(self, role: str, mount: str) -> bool:
        """Check if the role is created for the PKI backend."""
        try:
            existing_roles = self._client.list(f"/v1/{mount}/roles").json()
            return role in existing_roles["data"]["keys"]
        except InvalidPathError:
            return False

    def create_snapshot(self) -> requests.Response:
        """Create a snapshot of the OpenBao data."""
        return self._client.get("/v1/sys/storage/raft/snapshot", stream=True)

    def restore_snapshot(self, snapshot: IOBase) -> None:
        """Restore a snapshot of the OpenBao data.

        Uses force_restore_raft_snapshot to restore the snapshot
        even if the unseal key used at backup time is different from the current one.
        """
        response = self._client.post(
            "/v1/sys/storage/raft/snapshot-force", data=snapshot, raise_on_error=False
        )
        if not 200 <= response.status_code < 300:
            logger.warning("Error while restoring snapshot: %s", response.text)
            raise OpenBaoClientError(f"Error while restoring snapshot: {response.text}")

    def get_raft_cluster_state(self) -> dict:
        """Get raft cluster state."""
        response = self._client.get(RAFT_STATE_ENDPOINT)
        return response.json()["data"]

    def is_raft_cluster_healthy(self) -> bool:
        """Check if raft cluster is healthy."""
        return self.get_raft_cluster_state()["healthy"]

    def remove_raft_node(self, id: str) -> None:
        """Remove raft peer."""
        try:
            self._client.post("/v1/sys/storage/raft/remove-peer", json={"server_id": id})
        except (InternalServerError, ConnectionError) as e:
            logger.warning("Error while removing raft node: %s", e)
            return
        logger.info("Removed raft node %s", id)

    def is_node_in_raft_peers(self, id: str) -> bool:
        """Check if node is in raft peers."""
        try:
            raft_config = self._client.get("/v1/sys/storage/raft/configuration").json()
        except (InternalServerError, ConnectionError) as e:
            logger.warning("Error while reading raft config: %s", e)
            return False
        for peer in raft_config["data"]["config"]["servers"]:
            if peer["node_id"] == id:
                return True
        return False

    def get_num_raft_peers(self) -> int:
        """Return the number of raft peers."""
        try:
            raft_config = self._client.get("/v1/sys/storage/raft/configuration").json()
        except (InternalServerError, ConnectionError) as e:
            logger.warning("Error while reading raft config: %s", e)
            return 0
        return len(raft_config["data"]["config"]["servers"])

    def is_common_name_allowed_in_pki_role(self, role: str, mount: str, common_name: str) -> bool:
        """Return whether the provided common name is in the list of domains allowed by the specified PKI role."""
        try:
            role_data = self._client.get(f"/v1/{mount}/roles/{role}").json().get("data", {})
            return common_name in role_data.get("allowed_domains", [])
        except InvalidPathError:
            logger.warning("Role does not exist on the specified path.")
            return False

    def role_config_matches_given_config(
        self,
        role: str,
        mount: str,
        allowed_domains: List[str],
        allow_bare_domains: bool,
        allow_subdomains: bool,
        allow_wildcard_certificates: bool,
        allow_any_name: bool,
        allow_ip_sans: bool,
        organization: str | None,
        organizational_unit: str | None,
        country: str | None,
        province: str | None,
        locality: str | None,
    ) -> bool:
        """Return whether the role config matches the charm config."""
        try:
            role_data = self._client.get(f"/v1/{mount}/roles/{role}").json().get("data", {})

            if not all(
                common_name in role_data.get("allowed_domains", [])
                for common_name in allowed_domains
            ):
                return False

            expected_config = {
                "allow_bare_domains": allow_bare_domains,
                "allow_subdomains": allow_subdomains,
                "allow_wildcard_certificates": allow_wildcard_certificates,
                "allow_any_name": allow_any_name,
                "allow_ip_sans": allow_ip_sans,
                "organization": organization,
                "organizational_unit": organizational_unit,
                "country": country,
                "province": province,
                "locality": locality,
            }

            for field, expected_value in expected_config.items():
                if role_data.get(field) != expected_value:
                    return False

            return True
        except InvalidPathError:
            logger.warning("Role does not exist on the specified path.")
            return False

    def get_role_max_ttl(self, role: str, mount: str) -> int | None:
        """Get the max ttl for the specified PKI role in seconds."""
        try:
            return (
                self._client.get(f"/v1/{mount}/roles/{role}").json().get("data", {}).get("max_ttl")
            )
        except InvalidPathError:
            logger.warning("Role does not exist on the specified path.")
            return None

    def list_pki_issuers(self, mount: str) -> List[str]:
        """Get the list of issuers for the PKI backend.

        Args:
            mount: The mount point of the PKI backend.

        Returns:
            The list of issuers (i.e. ["issuer1", "issuer2"]).
        """
        try:
            return self._client.list(f"/v1/{mount}/issuers").json()["data"]["keys"]
        except (InvalidPathError, KeyError) as e:
            logger.error("No issuers found on the specified path: %s", e)
            raise OpenBaoClientError("No issuers found on the specified path.")

    def create_transit_key(self, mount_point: str, key_name: str) -> None:
        """Create a new key in the transit backend."""
        response = self._client.post(f"/v1/{mount_point}/keys/{key_name}", json={})
        logger.debug("Created a new transit key. response=%s", response)

    def delete_role(self, name: str) -> None:
        """Delete the approle with the given name."""
        self._client.delete(f"/v1/auth/approle/role/{name}")

    def delete_policy(self, name: str) -> None:
        """Delete the policy with the given name."""
        self._client.delete(f"/v1/sys/policy/{name}")

    def set_urls(
        self, mount: str, issuing_certificates: List[str], crl_distribution_points: List[str]
    ) -> None:
        """Set the URLs for the ACME backend."""
        self._client.post(
            f"/v1/{mount}/config/urls",
            json={
                "issuing_certificates": issuing_certificates,
                "crl_distribution_points": crl_distribution_points,
            },
        )

    def allow_acme_headers(self, mount: str) -> None:
        """Allow the ACME headers to be returned by the OpenBao server."""
        self._client.post(
            f"/v1/sys/mounts/{mount}/tune",
            json={"allowed_response_headers": ["Location", "Replay-Nonce", "Link"]},
        )


def generate_pem_bundle(certificate: str, private_key: str) -> str:
    """Generate a PEM bundle from a certificate and private key."""
    return f"{certificate}\n{private_key}"
