name: openbao
title: OpenBao
summary: The Snap for OpenBao
description: |
  A snap for Openbao, a community-driven fork of Vault managed by the Linux Foundation.

version: "v2.6.0"
base: core26
source-code: https://github.com/openbao/openbao
issues: https://github.com/canonical/openbao-omnicraft/issues
license: MPL-2.0
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:

grade: stable
confinement: strict

apps:
  bao:
    command: bin/bao
    plugs:
      - network
      - network-bind
      - home
  server:
    command: bin/baod-start
    plugs:
      - network
      - network-bind

    daemon: simple
    install-mode: disable
    refresh-mode: endure

    reload-command: bin/baod-reload
    stop-command: bin/baod-stop
    restart-condition: on-failure
    stop-mode: sigterm

parts:
  openbao:
    source: https://github.com/openbao/openbao.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-type: git
    source-depth: 1

    plugin: nil
    override-build: |
      make bootstrap
      corepack enable pnpm

      VERSION="$(git describe --tags --abbrev=0 | sed 's/^v//')"
      GIT_COMMIT="$(git rev-parse HEAD)"
      BUILD_DATE="$(git show --no-show-signature -s --format=%cd --date=format:'%Y-%m-%dT%H:%M:%SZ' HEAD)"
      export LD_FLAGS="-X github.com/openbao/openbao/version.fullVersion=${VERSION} -X github.com/openbao/openbao/version.GitCommit=${GIT_COMMIT} -X github.com/openbao/openbao/version.BuildDate=${BUILD_DATE}"

      make static-dist bin
      install -D -m755 bin/bao $SNAPCRAFT_PART_INSTALL/bin/bao

    build-snaps:
      - go/1.26/stable
    build-packages:
      - make
      - nodejs

  hooks:
    plugin: dump
    source: hooks
    organize:
      install: snap/hooks/install

  service-files:
    plugin: dump
    source: service

package-repositories:
 - type: apt
   url: https://deb.nodesource.com/node_20.x
   components: [main]
   suites: [nodistro]
   key-id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
