# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: OpenBao CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  continuous-delivery-snap:
    name: snap
    needs: continuous-integration
    if: needs.continuous-integration.outputs.snap-changed == 'true' || needs.continuous-integration.outputs.charm-machine-changed == 'true'
    uses: ./.github/workflows/cd-snap.yaml
    with:
      build: ${{ needs.continuous-integration.outputs.snap-changed == 'true' }}
  continuous-delivery-rock:
    name: rock
    needs: continuous-integration
    if: needs.continuous-integration.outputs.rock-changed == 'true' || needs.continuous-integration.outputs.charm-k8s-changed == 'true'
    uses: ./.github/workflows/cd-rock.yaml
    with:
      build: ${{ needs.continuous-integration.outputs.rock-changed == 'true' }}
