name: Snap CI

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 6 * * 0'

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - arch: amd64
            runner: '"ubuntu-24.04"'
          - arch: arm64
            runner: '["self-hosted", "linux", "ARM64", "medium", "noble"]'
          - arch: s390x
            runner: '["self-hosted-linux-s390x-noble-medium"]'
    uses: canonical/identity-credentials-workflows/.github/workflows/snap-build.yaml@v3.1.3
    with:
      path: snap/2.5.2
      arch: ${{ matrix.platform.arch }}
      runner: ${{ matrix.platform.runner }}

  test:
    needs: build
    uses: canonical/identity-credentials-workflows/.github/workflows/snap-test.yaml@v3.1.3
    with:
      artifacts-key: ${{ github.sha }}-build
      snap-name: openbao
      service-port: "8200"
      platforms: >-
        [{"arch": "amd64", "runner": "ubuntu-24.04"},
         {"arch": "arm64", "runner": ["self-hosted", "linux", "ARM64", "medium", "noble"]},
         {"arch": "s390x", "runner": ["self-hosted-linux-s390x-noble-medium"]}]

  track:
    name: Determine snap track
    if: ${{ github.ref_protected && github.event_name != 'pull_request' }}
    runs-on: ubuntu-24.04
    outputs:
      track: ${{ steps.track.outputs.track }}
    steps:
      - name: Get snapcraft track
        id: track
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "track=latest" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref_name }}" =~ ^stable\/(.+) ]]; then
            echo "track=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "Branch name does not match expected patterns. Exiting."
            exit 1
          fi

  publish:
    if: ${{ github.ref_protected && github.event_name != 'pull_request' }}
    needs: [build, test, track]
    strategy:
      matrix:
        arch: [amd64, arm64, s390x]
    uses: canonical/identity-credentials-workflows/.github/workflows/snap-publish.yaml@v3.1.3
    secrets:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    with:
      artifacts-key: ${{ github.sha }}-build-${{ matrix.arch }}
      track: ${{ needs.track.outputs.track }}
      channel: edge
