name: Auto-update Charm Libraries
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lib:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install charmcraft
        run: |
          sudo snap install charmcraft --classic --channel latest/stable

      - name: Fetch charm libraries (k8s)
        run: |
          cd charm/k8s
          charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_STORE_CREDENTIALS }}

      - name: Fetch charm libraries (machine)
        run: |
          cd charm/machine
          charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_STORE_CREDENTIALS }}

      - name: Create a PR for local changes
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: ${{ github.token }}
          sign-commits: true
          commit-message: "chore: update charm libraries"
          title: "chore: Update charm libraries"
          body: |
            Automated action to fetch latest version of charm libraries. The branch of this PR 
            will be wiped during the next check. Unless you really know what you're doing, you 
            most likely don't want to push any commits to this branch.
          branch: "chore/auto-libs"
          delete-branch: true
